env:
  browser: true
  node: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - "plugin:react-hooks/recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  indent:
    - warn
    - 2
    - SwitchCase: 1
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-console:
    - warn
    - allow:
        - error
  no-unused-vars:
    - warn
    - vars: all
      args: after-used
      ignoreRestSiblings: false
  keyword-spacing:
    - warn
    - after: true
  eqeqeq:
    - error
    - always
  space-infix-ops:
    - warn
    - int32Hint: false
  comma-spacing:
    - warn
    - before: false
      after: true
  brace-style: warn
  curly:
    - warn
    - multi-line
  no-multiple-empty-lines:
    - warn
    - max: 2
      maxEOF: 0
      maxBOF: 0
  operator-linebreak:
    - warn
    - after
  no-cond-assign: warn
  block-spacing: warn
  camelcase:
    - warn
    - properties: always
  comma-style:
    - warn
    - last
  dot-location:
    - warn
    - property
  func-call-spacing: warn
  key-spacing:
    - warn
    - beforeColon: false
  new-parens: warn
  no-debugger: warn
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-fallthrough: warn
  no-func-assign: error
  no-inner-declarations: error
  no-ex-assign: error
  no-return-assign: error
  no-self-assign: error
  no-sparse-arrays: warn
  no-template-curly-in-string: warn
  no-this-before-super: error
  no-throw-literal: error
  no-undef-init: error
  no-whitespace-before-property: warn
  object-property-newline: 
    - warn
    - allowAllPropertiesOnSameLine: true
  padded-blocks: 
    - warn
    - never
  semi-spacing: warn
  space-before-blocks: warn
  spaced-comment: warn
  template-curly-spacing: 
    - warn
    - never
  use-isnan: error
  valid-typeof: error
  wrap-iife: warn
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn